### ISSUE TITLE
Lock Screen in 0.3.6-1

### ISSUE THREAD

**Issue by johnlago** [peterhajas/MobileNotifier#85]
The new update seems to have broken notifications when the phone is locked. When a new notification comes in, the screen lights up and the vibrate/sound happens, but the notification itself is not displayed, and the MobileNotifier list shows up sporadically. Any chance of a quick fix for this? I may need to switch back to the native notifications to avoid missing some until this is fixed. Thanks!

**Comment by deluxestyle** [comment]
i have the same Problem.
No notification on the lock screen

**Comment by Kingfish** [comment]
Same here.  Phone (3GS on 4.2.1 GP jailbreak) wakes up when a notification comes in but nothing is on the lockscreen either plugged in or unplugged from AC.  I have to unlock and look at the AlertDashboard to see what app alerted me.

**Comment by peterhajas** [comment]
Resolved, will be pushed out in a future build.

**Comment by danakaz** [comment]
This is still an issue for me in beta 3.7-2. On a 3Gs 4.2.1.

**Comment by deluxestyle** [comment]
I have the same issue in beta3r7 on a iphone 4 with 4.2.1
